// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccpkpjuiqhlqxgfszjnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjcGtwanVpcWhscXhnZnN6am5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzY3NzIsImV4cCI6MjA2OTYxMjc3Mn0.IDkuKe8qbi7d9mWpabC2sTfD_DeRy9zouLqJXYVHWLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});